Sun Oct 31 19:28:49 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:AF:00.0 Off |                    0 |
| N/A   36C    P0    42W / 300W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
Master address: localhost
Master port: 1234
Number of nodes: 1
Number of GPUs per node: 1
Node rank: 0
Workspace: /project/def-karray/yafathi/MINE/
Dataset: kitti_raw
Version: debug
Extra config: {"training.gpus": "0"}
default params: ./configs/params_kitti_raw.yaml
/project/6006191/yafathi/MINE/synthesis_task_kitti.py:554: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  "epoch [%.3d] step [%d/%d] global_step = %d total_loss = %.4f encoder_lr = %.7f\n"
Dumping extra config file...
[2021-10-31 19:29:55,201 train.py] Training config: {'data.img_h': 128, 'data.img_w': 384, 'data.name': 'kitti_raw', 'data.img_pre_downsample_ratio': 7.875, 'data.num_seq_per_gpu': 4, 'data.per_gpu_batch_size': 4, 'data.num_tgt_views': 1, 'data.training_set_path': 'kitti_raw_data', 'data.val_set_path': 'YOUR_VAL_SET', 'data.visible_point_count': 256, 'data.num_workers': 4, 'data.rotation_pi_ratio': 3, 'data.is_exclude_views': True, 'lr.backbone_lr': 0.001, 'lr.decay_gamma': 0.1, 'lr.decay_steps': [40, 80, 100], 'lr.decoder_lr': 0.001, 'lr.weight_decay': 4e-05, 'model.backbone_normalization': True, 'model.decoder_normalization': True, 'model.pos_encoding_multires': 10, 'model.imagenet_pretrained': True, 'mpi.disparity_end': 0.001, 'mpi.disparity_start': 0.2, 'mpi.is_bg_depth_inf': False, 'mpi.num_bins_coarse': 32, 'mpi.num_bins_fine': 0, 'mpi.valid_mask_threshold': 2, 'mpi.fix_disparity': False, 'mpi.use_alpha': False, 'loss.smoothness_lambda_v1': 0.0, 'loss.smoothness_gmin': 2.0, 'loss.smoothness_grad_ratio': 0.1, 'loss.smoothness_lambda_v2': 0.01, 'training.epochs': 120, 'training.eval_interval': 2000, 'training.fine_tune': False, 'training.gpus': [0], 'training.pretrained_checkpoint_path': None, 'training.sample_interval': 30, 'training.src_rgb_blending': True, 'training.use_multi_scale': True, 'testing.frames_apart': 'random', 'current_epoch': 0, 'global_rank': 0, 'local_workspace': '/project/def-karray/yafathi/MINE/debug', 'local_rank': 0, 'world_size': 1, 'log_file': '/project/def-karray/yafathi/MINE/debug/training.log'}
Traceback (most recent call last):
  File "train.py", line 183, in <module>
    main()
  File "train.py", line 179, in main
    train()
  File "train.py", line 163, in train
    train_data_loader, val_data_loader = get_dataset(config, logger)
  File "train.py", line 102, in get_dataset
    train_dataset = NeRFDataset(config,
TypeError: __init__() got an unexpected keyword argument 'supervision_count'
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/project/6006191/yafathi/MINE_ENV/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/project/6006191/yafathi/MINE_ENV/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/project/6006191/yafathi/MINE_ENV/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/project/6006191/yafathi/MINE_ENV/bin/python3', '-u', 'train.py', '--local_rank=0', '--config_path', './configs/params_kitti_raw.yaml', '--workspace', '/project/def-karray/yafathi/MINE/', '--version', 'debug', '--extra_config', '{"training.gpus": "0"}']' returned non-zero exit status 1.
Killing subprocess 128481
